spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        format_sql: false
        use_sql_comments: true

  profiles:
    default: local

  cloud:
    aws:
      region:
        static: ap-northeast-2
      s3:
        bucket:
      stack:
        auto: false
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: ${JWT_SECRET}
  access-token-validity: ${ACCESS_TOKEN_VALIDITY_IN_MILLISECONDS}
  refresh-token-validity: ${REFRESH_TOKEN_VALIDITY_IN_MILLISECONDS}
  signup-token-validity: ${SIGNUP_TOKEN_VALIDITY_IN_MILLISECONDS}

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET}
  redirect-uri: ${KAKAO_REDIRECT_URI}
  authorization-uri: https://kauth.kakao.com/oauth/authorize
  token-uri: https://kauth.kakao.com/oauth/token
  user-info-uri: https://kapi.kakao.com/v2/user/me
  scope: account_email, profile, profile_image, openid

naver:
  client-id: ${NAVER_CLIENT_ID}
  client_secret: ${NAVER_CLIENT_SECRET}
  redirect-uri: ${NAVER_REDIRECT_URI}
  authorization-uri: https://nid.naver.com/oauth2.0/authorize
  token-uri: https://nid.naver.com/oauth2.0/token
  user-info-uri: https://openapi.naver.com/v1/nid/me
  scope: email, nickname


google:
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}
  redirect-uri: ${GOOGLE_REDIRECT_URI}
  authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
  token-uri: https://oauth2.googleapis.com/token
  user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
  scope:
    - https://www.googleapis.com/auth/userinfo.profile
    - https://www.googleapis.com/auth/userinfo.email


server:
  forward-headers-strategy: framework
  address: 0.0.0.0
  port: 8080

frontend:
  redirect-url: ${FRONTEND_REDIRECT_URL}

admin:
  super:
    email: whkang03@gmail.com
    provider-id: 4702854778
    oauth-provider: KAKAO


